Vagrant.configure("2") do |config|

    config.env.enable
    config.vm.box = ENV['vm_box']

    config.vm.define 'almalinux'

    # Size the guest from host resources (this Vagrantfile is evaluated on the Linux host).
    host_cpus = `nproc`.to_i
    host_ram  = `awk '/^MemTotal:/ {print $2}' /proc/meminfo`.to_i / 1024  # MiB (MemTotal is kB)
    guest_cpus = [host_cpus - 2, 1].max                                   # leave 2 cores for the host
    guest_ram  = [(host_ram * 0.75).to_i, 1024].max                       # 75% of host RAM, min 1 GiB

    config.vm.provider "libvirt" do |v|
        v.memory = guest_ram
        v.cpus = guest_cpus
        if ENV['vagrant_cpu_model']
            v.cpu_mode  = "custom"
            v.cpu_model = ENV['vagrant_cpu_model']
        end
    end

    config.vm.provision "shell", inline: <<-SHELL
        # Put in place almalinux-pungi.repo if exists
        test -e /vagrant/almalinux-pungi.repo && \
        sudo cp -av /vagrant/almalinux-pungi.repo /etc/yum.repos.d/almalinux-pungi.repo || \
        true

        # Put in place almalinux-pulp.repo if exists
        test -e /vagrant/almalinux-pulp.repo && \
        sudo cp -av /vagrant/almalinux-pulp.repo /etc/yum.repos.d/almalinux-pulp.repo || \
        true

        # Put in place almalinux-testing-pulp.repo if exists
        test -e /vagrant/almalinux-testing-pulp.repo && \
        sudo cp -av /vagrant/almalinux-testing-pulp.repo /etc/yum.repos.d/almalinux-testing-pulp.repo || \
        true

        # Put in place almalinux-nvidia-pulp.repo if exists
        test -e /vagrant/almalinux-nvidia-pulp.repo && \
        sudo cp -av /vagrant/almalinux-nvidia-pulp.repo /etc/yum.repos.d/almalinux-nvidia-pulp.repo || \
        true

        sudo dnf -y update
    SHELL

    # Reboot after update
    config.vm.provision :reload

end
